[package]
name = "experimental_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.0", features = ["derive"] }
cgmath = "0.18.0"
pollster = "0.2.0"
wgpu = "0.13.0"
winit = "0.26.0"
